version: "3.7"

services:
  # Watchtower - Auto update docker images
  watchtower:
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    network_mode: none
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --label-enable --cleanup --interval 300

  # Droplt GraphQL API
  graphql:
    image: droplt/graphql:latest
    depends_on:
      - watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    environment:
      - NODE_ENV=staging
      - PORT=4000
      - TRANSMISSION_HOST=${TRANSMISSION_HOST}
      - TRANSMISSION_PORT=${TRANSMISSION_PORT}
      - TRANSMISSION_USER=${TRANSMISSION_USER}
      - TRANSMISSION_PASS=${TRANSMISSION_PASS}
    ports:
      - 4000:4000

  # Transmission - BitTorrent client
  transmission:
    image: linuxserver/transmission:latest
    depends_on:
      - watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    volumes:
      # where transmission download torrent data
      - ./transmission/downloads:/downloads
      # where transmission stores its configuration, logs files
      - ./transmission/config:/config
      # transsmision will watch and automatically add .torrent files in this directory
      - ./transmission/watch:/watch
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
      - USER=${TRANSMISSION_USER}
      - PASS=${TRANSMISSION_PASS}
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp

  # Jackett - API support for torrent trackers
  jackett:
    image: linuxserver/jackett:latest
    depends_on:
      - watchtower
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    restart: always
    volumes:
      # where jackett stores its configuration, logs files
      - ./jackett/config:/config
      # where jackett download .torrent files
      - ./jackett/downloads:/downloads
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Paris
    ports:
      - 9117:9117
